### PR TITLE
fixes issue #54 Dutch language option disappears when reloading after switching to English

### PR DESCRIPTION
**Pull request by xavier-kong**

### CODE REVIEW

**Review by Marthijs-Berfelo — APPROVED** [review]

**Comment by Marthijs-Berfelo** [comment]
Nice fix! :+1: 
Please resolve the conflict, since this blocks merging

**Comment by Marthijs-Berfelo** [comment]
@xavier-kong I thnk it shouldn/t matter if you're merging the main or a branch from your fork.
However changes in the `package.lock.json` from your source branch conflict with the target. To avoid conflicts like that I use `npm ci` instead of `npm install` when getting the package dependencies. I only use install when I change dependencies.

Next to that it's easier to keep forks up to date with the original repository when working on the main branch in the fork.

**Comment by Marthijs-Berfelo** [comment]
fixes #54

**Comment by xavier-kong** [comment]
@Marthijs-Berfelo Ok I'll see what I can do. Sorry for the inconvenienced caused this is literally my first pull request!

**Review by Marthijs-Berfelo — APPROVED** [review]

**Comment by Marthijs-Berfelo** [comment]
@xavier-kong no worries :smile: I'm grateful for your contribution and always happy to help a fellow developer

**Pull request merged**
